const API_URL="https://script.google.com/macros/s/AKfycbyLxzC5iivkhOg8YbqqHXFfUppWk8gYSxN9k6eER-TyqvEpAh6DSQR1x1aeX0rFqa0h/exec";
const QUESTIONS=[{trait:"O",text:"我喜歡接觸沒體驗過的新事物。",reverse:false},{trait:"O",text:"比起嘗試新的方法，我通常更喜歡熟悉的做法。",reverse:true},{trait:"C",text:"開始做事情前，我通常會先安排好步驟。",reverse:false},{trait:"C",text:"我常常做到一半，才開始想下一步要做什麼。",reverse:true},{trait:"E",text:"和一群人在一起時，我通常會主動加入互動。",reverse:false},{trait:"E",text:"在熱鬧的場合中，我通常比較喜歡待在旁邊。",reverse:true},{trait:"A",text:"我很容易注意到別人的感受。",reverse:false},{trait:"A",text:"意見不同時，我通常不太在意對方的感受。",reverse:true},{trait:"N",text:"我的情緒很容易受到周遭事情影響。",reverse:false},{trait:"N",text:"面對壓力或突發狀況時，我通常很快就能平靜下來。",reverse:true}];
const TYPES={O:{name:"EXPLORER",subtitle:"The Blue Planet",color:"#4ba9ff",light:"#a9e4ff",dark:"#163a9e",word:"curious",description:"你以好奇心探索未知，喜歡新的想法與體驗。你的世界充滿想像，也總能從不同角度看見可能。"},C:{name:"ARCHITECT",subtitle:"The Green Planet",color:"#60d394",light:"#c3ffe1",dark:"#166650",word:"structured",description:"你擅長建立秩序，將想法一步步變成現實。穩定、專注與責任感，是你的星球持續運轉的力量。"},E:{name:"SPARK",subtitle:"The Yellow Planet",color:"#ffd15c",light:"#fff2b6",dark:"#9b5d12",word:"radiant",description:"你從交流與行動中獲得能量，願意表達也樂於連結。你的存在像一道光，為周遭帶來活力。"},A:{name:"HARMONIZER",subtitle:"The Pink Planet",color:"#ff80b7",light:"#ffd0e6",dark:"#8c2857",word:"harmonious",description:"你能感受他人的需要，重視理解、合作與溫柔。你讓不同的聲音找到平衡，也讓關係產生連結。"},N:{name:"SENSITIVE",subtitle:"The Gray Planet",color:"#a9afc3",light:"#eff1fa",dark:"#555d78",word:"sensitive",description:"你對環境與情緒的變化格外敏銳。細膩的感受力，讓你看見容易被忽略的訊號與深層情感。"}};
const DEMO=[["O",82,57,71,64,38],["A",56,61,44,88,52],["C",49,91,39,72,35],["E",66,52,93,70,41],["N",73,46,35,67,89],["O",94,68,55,48,43],["C",58,84,62,63,31],["A",47,72,53,92,58],["E",69,44,86,57,46],["O",87,51,76,70,62],["N",65,53,40,74,84],["A",77,69,58,86,39]].map((d,i)=>({id:`DEMO${String(i+1).padStart(3,"0")}`,nickname:"Traveler",type:d[0],scores:{O:d[1],C:d[2],E:d[3],A:d[4],N:d[5]},seed:1100+i*97}));
let currentQuestion=0,answers=[],currentResult=null,profileData=null,universeData=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],sleep=ms=>new Promise(r=>setTimeout(r,ms));
function showScreen(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo(0,0);if(id==='universe')loadUniverse()}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.go)));$('#start-test').addEventListener('click',()=>showScreen('profile'));$('#restart-test').addEventListener('click',()=>showScreen('profile'));$('#enter-universe').addEventListener('click',()=>showScreen('universe'));
initBirthdaySelects();
$('#profile-form').addEventListener('submit',e=>{e.preventDefault();const year=$('#birth-year').value,month=$('#birth-month').value.padStart(2,'0'),day=$('#birth-day').value.padStart(2,'0');profileData={nickname:$('#nickname').value.trim(),birthYear:Number(year),birthMonth:Number(month),birthDay:Number(day),birthday:`${year}-${month}-${day}`,consent:$('#consent').checked};startTest()});
function initBirthdaySelects(){const year=$('#birth-year'),month=$('#birth-month'),now=new Date().getFullYear();for(let y=now;y>=1900;y--)year.add(new Option(`${y} 年`,y));for(let m=1;m<=12;m++)month.add(new Option(`${m} 月`,m));year.addEventListener('change',updateBirthDays);month.addEventListener('change',updateBirthDays);updateBirthDays()}
function updateBirthDays(){const day=$('#birth-day'),selected=day.value,year=Number($('#birth-year').value)||2000,month=Number($('#birth-month').value);day.innerHTML='<option value="">日</option>';if(!month)return;const count=new Date(year,month,0).getDate();for(let d=1;d<=count;d++)day.add(new Option(`${d} 日`,d));if(Number(selected)<=count)day.value=selected}
function startTest(){currentQuestion=0;answers=[];showScreen('test');renderQuestion()}
function renderQuestion(){const q=QUESTIONS[currentQuestion];$('#question-counter').textContent=`${String(currentQuestion+1).padStart(2,'0')} / 10`;$('#question-tag').textContent=`QUESTION ${String(currentQuestion+1).padStart(2,'0')}`;$('#question-title').textContent=q.text;$('#progress-bar').style.width=`${(currentQuestion+1)*10}%`;const scale=$('#answer-scale');scale.innerHTML='';for(let v=1;v<=5;v++){const b=document.createElement('button');b.className='answer';b.dataset.value=v;b.setAttribute('role','radio');b.setAttribute('aria-label',`${v} 分`);b.addEventListener('click',()=>selectAnswer(v));scale.appendChild(b)}}
function selectAnswer(v){answers[currentQuestion]=v;if(currentQuestion<9){currentQuestion++;setTimeout(renderQuestion,180)}else finishTest()}
$('#test-back').addEventListener('click',()=>{if(currentQuestion===0)showScreen('profile');else{currentQuestion--;renderQuestion()}});
async function finishTest(){const adjustedAnswers=QUESTIONS.map((q,i)=>q.reverse?6-answers[i]:answers[i]),raw={O:0,C:0,E:0,A:0,N:0};QUESTIONS.forEach((q,i)=>raw[q.trait]+=adjustedAnswers[i]);const scores=Object.fromEntries(Object.entries(raw).map(([k,v])=>[k,Math.round((v-2)/8*100)])),ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]),type=ranked[0][0],secondaryType=ranked[1][0],seed=birthdaySeed(profileData.birthday),keywords=birthKeywords(profileData.birthday,type);currentResult={id:createId(),...profileData,questions:QUESTIONS.map((q,i)=>({number:i+1,trait:q.trait,text:q.text,reverse:q.reverse})),answers:[...answers],adjustedAnswers,rawScores:raw,ranking:ranked.map(([trait,score])=>({trait,score})),birthdaySeed:seed,type,secondaryType,scores,initialKeywords:[...keywords],keywords,seed,createdAt:new Date().toISOString(),status:'generating',aiStatus:'pending',tripoStatus:'pending'};currentResult.fallbackPrompt=buildTripoPrompt(currentResult);currentResult.prompt=currentResult.fallbackPrompt;showScreen('forming');setGenerationProgress(4,'AI IS READING YOUR INNER WORLD','正在融合人格分數與生日的太陽星座象徵。');try{const ai=await apiPost({action:'ai_planet_design',nickname:currentResult.nickname,birthday:currentResult.birthday,type,secondaryType,scores});Object.assign(currentResult,{planetName:ai.design.planetName,astroSummary:ai.design.astroSummary,keywords:ai.design.keywords,description:ai.design.description,prompt:ai.design.tripoPrompt,aiStatus:'success',aiModel:ai.model,aiCompletedAt:ai.completedAt});setGenerationProgress(12,'AI DESIGN COMPLETE','專屬星球設定完成，正在交給 Tripo 建模。')}catch(error){console.warn(error);currentResult.aiStatus='failed';currentResult.aiError=error.message;toast('GPT 設計暫時無法使用，改用內建生成規則')}try{const created=await apiPost({action:'tripo_create',prompt:currentResult.prompt});currentResult.tripoTaskId=created.taskId;currentResult.tripoStatus='processing';await pollTripoTask(created.taskId)}catch(error){console.warn(error);currentResult.status='fallback';currentResult.tripoStatus='failed';currentResult.generationError=error.message;toast(/credit/i.test(error.message)?'Tripo 生成額度不足，先顯示程序化星球':'Tripo 生成失敗，先顯示程序化星球')}renderResult();showScreen('result');await savePlanet(currentResult)}
function birthdaySeed(date){return Number(date.replaceAll('-','').slice(2))||Math.floor(Math.random()*900000)+100000}
function birthKeywords(date,type){const [,m,d]=date.split('-').map(Number),md=m*100+d,signs=[[120,'disciplined'],[219,'visionary'],[321,'dreamy'],[420,'bold'],[521,'grounded'],[621,'adaptive'],[723,'nurturing'],[823,'radiant'],[923,'refined'],[1023,'balanced'],[1122,'mysterious'],[1222,'adventurous'],[1232,'disciplined']],sign=signs.find(([limit])=>md<limit)||signs[0];let sum=date.replaceAll('-','').split('').reduce((a,n)=>a+Number(n),0);while(sum>9)sum=String(sum).split('').reduce((a,n)=>a+Number(n),0);const nums={1:'independent',2:'harmonious',3:'expressive',4:'stable',5:'free',6:'caring',7:'introspective',8:'powerful',9:'compassionate'};return[TYPES[type].word,sign[1],nums[sum]]}
function buildTripoPrompt(p){const main=TYPES[p.type],second=TYPES[p.secondaryType],s=p.scores,ocean=s.O>60?'deep luminous oceans and imaginative organic islands':'calm enclosed seas and clean coastlines',terrain=s.C>60?'carefully structured mountain ranges and ordered surface patterns':'free-flowing natural terrain',energy=s.E>60?'a bright radiant core and glowing crystal formations':'a quiet soft inner glow',nature=s.A>60?'gentle vegetation and harmonious atmospheric details':'minimal resilient vegetation',weather=s.N>60?'dramatic cloud formations and emotional surface variation':'clear atmosphere and peaceful weather';return`A complete spherical fantasy planet as one isolated 3D object. ${main.name} personality blended with ${second.name}. Keywords: ${p.keywords.join(', ')}. ${ocean}, ${terrain}, ${energy}, ${nature}, ${weather}. Main color ${main.color}, secondary color ${second.color}, silver-white accents. Elegant stylized high-quality game-ready 3D asset, detailed PBR surface, clean topology, centered, fully visible round planet, no background, no text, no stand, no characters, no spaceship, no extra planets.`}
async function apiPost(body){const res=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)}),json=await res.json();if(!res.ok||!json.success)throw new Error(json.message||'API request failed');return json}
async function pollTripoTask(taskId){for(let attempt=0;attempt<45;attempt++){await sleep(attempt===0?1800:3000);const res=await fetch(`${API_URL}?action=tripo_status&taskId=${encodeURIComponent(taskId)}`),json=await res.json();if(!json.success)throw new Error(json.message||'Unable to read Tripo status');const progress=Math.max(8,Math.min(99,Number(json.progress)||attempt*2+8));currentResult.tripoProgress=progress;currentResult.tripoStatus=json.status;setGenerationProgress(progress,'TRIPO IS BUILDING YOUR WORLD',generationMessage(progress));if(json.status==='success'){if(!json.modelUrl)throw new Error(`Tripo 完成但沒有模型網址（output: ${(json.outputKeys||[]).join(', ')||'empty'}）`);currentResult.status='ready';currentResult.tripoStatus='success';currentResult.tripoProgress=100;currentResult.tripoCompletedAt=new Date().toISOString();currentResult.modelUrl=json.modelUrl;currentResult.thumbnailUrl=json.thumbnailUrl||'';setGenerationProgress(100,'YOUR PLANET IS READY','正在將星球送入共享宇宙。');await sleep(800);return}if(['failed','cancelled','banned'].includes(json.status))throw new Error(`Tripo task ${json.status}`)}throw new Error('Tripo generation timed out')}
function generationMessage(p){if(p<25)return'正在建立星球輪廓與地形。';if(p<55)return'正在生成海洋、生態與山脈。';if(p<85)return'正在加入材質、色彩與光澤。';return'正在完成專屬 3D 星球。'}
function setGenerationProgress(p,stage,message){$('#generation-bar').style.width=`${p}%`;$('#generation-number').textContent=`${Math.round(p)}%`;$('#forming-stage').textContent=stage;$('#forming-message').textContent=message}
function createId(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function renderResult(){const t=TYPES[currentResult.type],root=document.documentElement;root.style.setProperty('--type-color',t.color);root.style.setProperty('--planet-glow',t.color+'88');$('#result-code').textContent=`${currentResult.nickname} · TYPE ${currentResult.type}`;$('#result-name').textContent=currentResult.planetName||t.name;$('#result-subtitle').textContent=currentResult.planetName?`${t.name} · ${t.subtitle}`:t.subtitle;$('#result-description').textContent=currentResult.description||t.description;$('#planet-id').textContent=`PLANET #${currentResult.id}`;$('#result-planet').style.background=`radial-gradient(circle at 36% 32%,${t.light},${t.color} 30%,${t.dark} 66%,#07091b 100%)`;$('#birth-keywords').innerHTML=currentResult.keywords.map(k=>`<span>${k.toUpperCase()}</span>`).join('');$('#score-list').innerHTML=Object.entries(currentResult.scores).map(([k,v])=>`<div class="score-row"><label>${k}</label><div class="score-bar"><i style="--bar:${TYPES[k].color};width:${v}%"></i></div><span>${v}</span></div>`).join('');const model=$('#result-model'),status=$('#result-model-status'),visual=$('.result-visual');visual.classList.remove('has-model');status.textContent=currentResult.modelUrl?'正在載入 3D 模型…':'目前顯示概念星球，尚無 3D 模型';showPoster($('#result-poster'),currentResult.thumbnailUrl,visual);if(currentResult.modelUrl)setModelSource(model,currentResult.modelUrl,visual,status);else model.removeAttribute('src');renderPersonalityAnalysis(currentResult)}
const TRAIT_ANALYSIS={
  O:{title:'開放性',high:'你樂於嘗試新想法，容易對未知事物產生好奇，也常能從不同角度找到靈感。',mid:'你會在熟悉的方法與新鮮的體驗之間調整，依情境決定要探索還是維持穩定。',low:'你重視熟悉與實用的做法，面對變化時傾向先掌握脈絡，再決定是否嘗試。',tip:'想法很多時，先挑一個小實驗落地。',planet:'海洋、島嶼與多變地形'},
  C:{title:'盡責性',high:'你習慣規劃步驟並完成承諾，讓想法能穩定地累積成成果。',mid:'你能依任務調整節奏，有時先安排流程，有時保留即興空間。',low:'你偏好彈性與即時反應，當計畫需要長期推進時，清楚的小目標會有幫助。',tip:'繁忙時只排最重要的下一步，保留喘息空間。',planet:'有秩序的山脈與地表紋理'},
  E:{title:'外向性',high:'你容易從交流與行動取得能量，也願意主動把想法帶到人群之中。',mid:'你能享受互動，也需要自己的節奏，通常會看場合決定投入程度。',low:'你傾向先觀察再表達，安靜與獨處可能讓你更容易整理感受。',tip:'在合作時說出你需要的互動與獨處時間。',planet:'星球核心的亮度與光點'},
  A:{title:'親和性',high:'你能留意他人的感受，重視理解與合作，願意為關係建立溫柔的連結。',mid:'你會在照顧他人與維持自身界線間尋找平衡。',low:'你更願意直接說出不同意見，能幫團隊看見被忽略的問題。',tip:'在體貼別人的同時，也把自己的需求說清楚。',planet:'植物、生態與柔和大氣'},
  N:{title:'情緒敏感度',high:'你對壓力與環境變化較敏銳，能察覺細微訊號；緊繃時也可能需要較多恢復時間。',mid:'你對情緒有一定感受力，多數時候能隨情境調整回應。',low:'你面對壓力時相對容易保持平靜，能為周遭帶來穩定感。',tip:'情緒強烈時先休息、命名感受，再決定要怎麼回應。',planet:'雲層、天氣與表面光影'}
};
function analysisBand(score){return score>=67?'high':score>=34?'mid':'low'}
function renderPersonalityAnalysis(p){const section=$('#personality-analysis');section.replaceChildren();const title=document.createElement('h3');title.textContent='你的完整人格分析';section.appendChild(title);const scores=p.scores||{},rank=Object.entries(scores).sort((a,b)=>b[1]-a[1]),lead=rank[0]?.[0]||'O',second=rank[1]?.[0]||'C';const summary=document.createElement('p');summary.className='analysis-summary';summary.textContent=`你的主要傾向是${TRAIT_ANALYSIS[lead].title}，其次是${TRAIT_ANALYSIS[second].title}。這代表你在這份十題測驗中，最常展現${TRAIT_ANALYSIS[lead][analysisBand(scores[lead])]} 星球的設計也會把這兩個面向一起呈現。`;section.appendChild(summary);const grid=document.createElement('div');grid.className='analysis-grid';for(const [key,trait] of Object.entries(TRAIT_ANALYSIS)){const score=Number(scores[key])||0,card=document.createElement('article'),heading=document.createElement('h4'),body=document.createElement('p'),mapping=document.createElement('small');heading.textContent=`${trait.title} · ${score}/100`;body.textContent=trait[analysisBand(score)];mapping.textContent=`星球對應：${trait.planet}。${trait.tip}`;card.append(heading,body,mapping);grid.appendChild(card)}section.appendChild(grid);const note=document.createElement('p');note.className='analysis-note';note.textContent='分數根據每個面向兩道題估算，只反映這次回答；沒有好壞之分，也不是臨床診斷。生日僅作星球創作的象徵素材。';section.appendChild(note)}
function showPoster(img,url,container){container.classList.remove('has-poster');img.removeAttribute('src');if(!url)return;img.onload=()=>container.classList.add('has-poster');img.onerror=()=>container.classList.remove('has-poster');img.src=url}
function wireModelViewer(model,container,status){model.addEventListener('load',()=>{container.classList.add('has-model');status.textContent='';model.setAttribute('camera-controls','')});model.addEventListener('error',()=>{container.classList.remove('has-model');status.textContent=container.classList.contains('has-poster')?'已顯示模型預覽，3D 暫時無法載入':'模型載入失敗，請重新選取星球';console.warn('3D model could not be loaded')})}
function setModelSource(model,url,container,status){model.setAttribute('src',url);setTimeout(()=>{if(model.getAttribute('src')===url&&!container.classList.contains('has-model')&&status.textContent.includes('載入'))status.textContent=container.classList.contains('has-poster')?'已顯示模型預覽；3D 需要瀏覽器啟用 WebGL':'3D 無法顯示；請確認瀏覽器已啟用 WebGL，或重新選取星球'},20000)}
wireModelViewer($('#result-model'),$('.result-visual'),$('#result-model-status'));
wireModelViewer($('#card-model'),$('.card-model-wrap'),$('#card-model-status'));
async function savePlanet(planet){const saved=JSON.parse(localStorage.getItem('innerversePlanets')||'[]');saved.unshift(planet);localStorage.setItem('innerversePlanets',JSON.stringify(saved.slice(0,50)));try{await apiPost({action:'create',...planet});toast('你的星球已存入宇宙')}catch(e){toast('星球已保存在此裝置，雲端儲存失敗')}}
async function loadUniverse(){const local=JSON.parse(localStorage.getItem('innerversePlanets')||'[]');universeData=[...local,...DEMO];try{const res=await fetch(`${API_URL}?action=list`),json=await res.json();if(json.success&&json.data.length)universeData=[...json.data,...DEMO.slice(0,6)]}catch(e){toast('已顯示本機宇宙')}renderUniverse(universeData);resetFilter()}
let cosmosRequest=0;
function renderUniverse(data){const request=++cosmosRequest;$('#planet-count').textContent=data.length;const cosmos=$('#cosmos');cosmos.replaceChildren();const tasks=[];data.forEach((p,i)=>{const t=TYPES[p.type]||TYPES.O,rng=mulberry32(Number(p.seed)||i+8),generated=Boolean(p.tripoTaskId),size=Math.round((generated?72:28)+rng()*(generated?40:48)),btn=document.createElement('button');btn.className='cosmos-planet';btn.dataset.type=p.type;btn.style.cssText=`--size:${size}px;--color:${t.color};--light:${t.light};--dark:${t.dark};--glow:${t.color}66;--speed:${4+rng()*4}s;--delay:${-rng()*5}s;--rotate:${rng()*160}deg;width:${size}px;height:${size}px;left:${4+rng()*88}%;top:${5+rng()*82}%`;btn.setAttribute('aria-label',`${t.name} 星球 ${p.id}`);if(generated){const poster=document.createElement('img'),viewer=document.createElement('model-viewer'),status=document.createElement('span');poster.className='cosmos-poster';poster.alt='';viewer.setAttribute('loading','eager');viewer.setAttribute('auto-rotate','');viewer.setAttribute('environment-image','neutral');viewer.setAttribute('shadow-intensity','1');viewer.setAttribute('interaction-prompt','none');viewer.setAttribute('alt',`${p.nickname||t.name} 的 3D 星球`);status.className='sr-only';btn.append(poster,viewer,status);viewer.addEventListener('load',()=>btn.classList.add('has-model'));viewer.addEventListener('error',()=>btn.classList.remove('has-model'));tasks.push({p,btn,poster,viewer,status})}btn.addEventListener('click',()=>selectPlanet(p));cosmos.appendChild(btn)});tasks.reverse();let next=0;async function worker(){while(next<tasks.length){const item=tasks[next++];try{const res=await fetch(`${API_URL}?action=tripo_status&taskId=${encodeURIComponent(item.p.tripoTaskId)}`),data=await res.json();if(request!==cosmosRequest)return;if(data.success&&data.status==='success'){showPoster(item.poster,data.thumbnailUrl,item.btn);if(data.modelUrl)setModelSource(item.viewer,data.modelUrl,item.btn,item.status)}}catch(error){console.warn('宇宙模型讀取失敗:',error.message)}}}for(let i=0;i<Math.min(3,tasks.length);i++)worker()}
let selectedPlanetRequest=0,selectedPlanet=null;
async function selectPlanet(p){selectedPlanet=p;const request=++selectedPlanetRequest;$$('.cosmos-planet').forEach(x=>{x.classList.toggle('dimmed',x.dataset.type!==p.type);x.classList.toggle('highlight',x.dataset.type===p.type)});$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===p.type));const t=TYPES[p.type]||TYPES.O,model=$('#card-model'),status=$('#card-model-status'),wrap=$('.card-model-wrap');$('#planet-card').classList.add('open');$('#planet-card').style.setProperty('--card-color',t.color);$('#card-type').textContent=`TYPE ${p.type} · ${t.subtitle}`;$('#card-name').textContent=p.nickname||t.name;$('#card-id').textContent=`PLANET #${p.id}`;$('#card-analysis').textContent=`${TRAIT_ANALYSIS[p.type]?.title||'人格特質'}：${TRAIT_ANALYSIS[p.type]?.[analysisBand(p.scores?.[p.type]||0)]||''}`;$('#card-scores').innerHTML=Object.entries(p.scores).map(([k,v])=>`<div class="card-score"><span>${k}</span><span>${v}</span></div>`).join('');wrap.classList.remove('has-model');model.removeAttribute('src');showPoster($('#card-poster'),p.thumbnailUrl,wrap);status.textContent=p.tripoTaskId?'正在取得 3D 模型…':'這顆星球尚無 3D 模型';if(!p.tripoTaskId)return;try{const response=await fetch(`${API_URL}?action=tripo_status&taskId=${encodeURIComponent(p.tripoTaskId)}`),data=await response.json();if(request!==selectedPlanetRequest)return;if(!data.success||data.status!=='success'||!data.modelUrl)throw new Error(data.message||'模型尚未準備好');p.modelUrl=data.modelUrl;p.thumbnailUrl=data.thumbnailUrl||p.thumbnailUrl;showPoster($('#card-poster'),p.thumbnailUrl,wrap);status.textContent='正在載入 3D 模型…';setModelSource(model,p.modelUrl,wrap,status)}catch(error){if(request!==selectedPlanetRequest)return;status.textContent='暫時無法讀取模型，請稍後重試';console.warn('Tripo model status unavailable:',error.message)}}
$('#open-planet-result').addEventListener('click',async()=>{if(!selectedPlanet)return;const p=selectedPlanet;currentResult={...p,keywords:p.keywords||[],scores:p.scores||{O:0,C:0,E:0,A:0,N:0}};if(p.tripoTaskId){try{const response=await fetch(`${API_URL}?action=tripo_status&taskId=${encodeURIComponent(p.tripoTaskId)}`),data=await response.json();if(data.success&&data.status==='success'){currentResult.modelUrl=data.modelUrl;currentResult.thumbnailUrl=data.thumbnailUrl||p.thumbnailUrl}}catch(error){console.warn('星球模型更新失敗:',error.message)}}renderResult();showScreen('result')});
$('#close-card').addEventListener('click',()=>{$('#planet-card').classList.remove('open');resetFilter()});$('#filter-bar').addEventListener('click',e=>{const b=e.target.closest('.filter');if(!b)return;const f=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));$$('.cosmos-planet').forEach(x=>{x.classList.toggle('dimmed',f!=='ALL'&&x.dataset.type!==f);x.classList.toggle('highlight',f!=='ALL'&&x.dataset.type===f)});$('#planet-card').classList.remove('open')});
function resetFilter(){$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='ALL'));$$('.cosmos-planet').forEach(x=>x.classList.remove('dimmed','highlight'))}function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3000)}
const canvas=$('#starfield'),ctx=canvas.getContext('2d');let stars=[];function resizeStars(){const d=Math.min(devicePixelRatio,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0);stars=Array.from({length:Math.round(innerWidth*innerHeight/8000)},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.25+.15,a:Math.random()*.7+.15,s:Math.random()*.006+.002}))}function drawStars(t=0){ctx.clearRect(0,0,innerWidth,innerHeight);for(const s of stars){ctx.globalAlpha=s.a*(.65+.35*Math.sin(t*s.s));ctx.fillStyle='#e9e8ff';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(drawStars)}addEventListener('resize',resizeStars);resizeStars();drawStars();addEventListener('scroll',()=>$('.site-header').classList.toggle('scrolled',scrollY>15));
