const SPREADSHEET_ID='17_HK3OGjiSa5UvjkzK96VPpIQM5c65yqOUPGGF1lKks';
const SHEET_NAME='planets_v3';
const TRIPO_BASE_URL='https://openapi.tripo3d.ai/v3';
function doGet(e){try{const action=String(e.parameter.action||'list').toLowerCase();if(action==='list')return json({success:true,data:listPlanets()});if(action==='tripo_status')return getTripoStatus(e.parameter.taskId);return json({success:false,message:'Unknown action'})}catch(err){return json({success:false,message:err.message})}}
function doPost(e){try{const body=JSON.parse(e.postData.contents||'{}');if(body.action==='ai_planet_design')return createAiPlanetDesign(body);if(body.action==='tripo_create')return createTripoTask(body.prompt);if(body.action==='create')return savePlanet(body);return json({success:false,message:'Unknown action'})}catch(err){return json({success:false,message:err.message})}}
function createAiPlanetDesign(body){
  if(!body.birthday||!/^[OCEAN]$/.test(body.type))throw new Error('生日或人格資料不完整');
  const schema={type:'object',additionalProperties:false,properties:{planetName:{type:'string'},astroSummary:{type:'string'},keywords:{type:'array',items:{type:'string'},minItems:3,maxItems:3},description:{type:'string'},tripoPrompt:{type:'string'}},required:['planetName','astroSummary','keywords','description','tripoPrompt']};
  const instructions='你是 INNERVERSE 的人格與幻想星球設計師。根據 Big Five 分數與生日的太陽星座象徵，創造一致且可視覺化的星球設定。生日只能可靠判斷太陽星座；沒有出生時間與地點時，禁止宣稱已計算月亮、上升、宮位或完整本命盤。占星內容只作創意與娛樂用途。輸出繁體中文，但 tripoPrompt 必須是清楚具體的英文。Prompt 必須描述單一完整球形行星、置中、全貌、無背景、無文字、無底座、無人物、無太空船、無額外行星，並包含材質、地形、生態、雲層、發光特徵、配色與 PBR 風格。';
  const input=JSON.stringify({nickname:safe(body.nickname),birthday:safe(body.birthday),primaryType:body.type,secondaryType:safe(body.secondaryType),bigFiveScores:body.scores||{},designConstraints:{keywords:'恰好三個、每個二至四個中文字',tripoPromptMaxCharacters:950}});
  const result=callOpenAI({model:getOpenAiModel(),instructions:instructions,input:input,text:{format:{type:'json_schema',name:'planet_design',strict:true,schema:schema}}});
  const design=JSON.parse(extractOpenAiText(result));
  if(!design.tripoPrompt||!Array.isArray(design.keywords)||design.keywords.length!==3)throw new Error('GPT 回傳的星球設計格式不完整');
  return json({success:true,design:design});
}
function getOpenAiModel(){return PropertiesService.getScriptProperties().getProperty('OPENAI_MODEL')||'gpt-5-mini'}
function callOpenAI(payload){const apiKey=PropertiesService.getScriptProperties().getProperty('OPENAI_API_KEY');if(!apiKey)throw new Error('OPENAI_API_KEY 尚未設定');const response=UrlFetchApp.fetch('https://api.openai.com/v1/responses',{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+apiKey},payload:JSON.stringify(payload),muteHttpExceptions:true}),status=response.getResponseCode(),text=response.getContentText();let data;try{data=JSON.parse(text)}catch(_){throw new Error('OpenAI 回傳非 JSON 資料')}if(status<200||status>=300)throw new Error((data.error&&data.error.message)||('OpenAI API error '+status));return data}
function extractOpenAiText(response){let texts=[];(response.output||[]).forEach(function(item){(item.content||[]).forEach(function(content){if(content.type==='output_text'&&content.text)texts.push(content.text)})});if(!texts.length)throw new Error('GPT 沒有回傳星球設計');return texts.join('')}
function createTripoTask(prompt){if(!prompt||prompt.length<20)throw new Error('Planet prompt is missing');const result=callTripo('/generation/text-to-model','post',{prompt:String(prompt).slice(0,1000),model:'v3.1-20260211'});if(!result.data||!result.data.task_id)throw new Error('Tripo did not return a task ID');return json({success:true,taskId:result.data.task_id})}
function getTripoStatus(taskId){if(!taskId)throw new Error('Tripo task ID is missing');const result=callTripo('/tasks/'+encodeURIComponent(taskId),'get'),task=result.data||{},output=task.output||{};return json({success:true,taskId:task.task_id||taskId,status:task.status||'unknown',progress:Number(task.progress||0),modelUrl:output.model_url||'',thumbnailUrl:output.rendered_image_url||'',message:task.message||''})}
function callTripo(path,method,payload){const apiKey=PropertiesService.getScriptProperties().getProperty('TRIPO_API_KEY');if(!apiKey)throw new Error('TRIPO_API_KEY 尚未設定');const options={method:method,headers:{Authorization:'Bearer '+apiKey},muteHttpExceptions:true};if(payload){options.contentType='application/json';options.payload=JSON.stringify(payload)}const response=UrlFetchApp.fetch(TRIPO_BASE_URL+path,options),status=response.getResponseCode(),text=response.getContentText();let data;try{data=JSON.parse(text)}catch(_){throw new Error('Tripo 回傳非 JSON 資料')}if(status<200||status>=300||data.code!==0)throw new Error((data&&(data.message||data.msg))||('Tripo API error '+status));return data}
function savePlanet(body){if(!/^[OCEAN]$/.test(body.type))throw new Error('Invalid personality type');const s=body.scores||{};getSheet().appendRow([safe(body.id),safe(body.nickname),safe(body.type),safe(body.secondaryType),number(s.O),number(s.C),number(s.E),number(s.A),number(s.N),JSON.stringify(body.keywords||[]),number(body.birthdaySeed),number(body.seed),safe(body.status),safe(body.tripoTaskId),safe(body.modelUrl),safe(body.thumbnailUrl),safe(body.prompt),safe(body.createdAt||new Date().toISOString()),safe(body.planetName),safe(body.astroSummary),safe(body.description)]);return json({success:true,id:body.id})}
function listPlanets(){const rows=getSheet().getDataRange().getValues();return rows.slice(1).filter(r=>r[0]).map(r=>({id:String(r[0]),nickname:String(r[1]),type:String(r[2]),secondaryType:String(r[3]),scores:{O:Number(r[4]),C:Number(r[5]),E:Number(r[6]),A:Number(r[7]),N:Number(r[8])},keywords:parseArray(r[9]),birthdaySeed:Number(r[10]),seed:Number(r[11]),status:String(r[12]),tripoTaskId:String(r[13]),modelUrl:String(r[14]),thumbnailUrl:String(r[15]),prompt:String(r[16]),createdAt:r[17],planetName:String(r[18]),astroSummary:String(r[19]),description:String(r[20])}))}
function getSheet(){const book=SpreadsheetApp.openById(SPREADSHEET_ID);let sheet=book.getSheetByName(SHEET_NAME);if(!sheet){sheet=book.insertSheet(SHEET_NAME);sheet.appendRow(['id','nickname','type','secondary_type','O','C','E','A','N','keywords','birthday_seed','seed','status','tripo_task_id','model_url','thumbnail_url','prompt','created_at','planet_name','astro_summary','description']);sheet.setFrozenRows(1)}return sheet}
function parseArray(value){try{return JSON.parse(value||'[]')}catch(_){return[]}}
function safe(value){return value==null?'':String(value).slice(0,5000)}
function number(value){const n=Number(value);return isFinite(n)?n:0}
function json(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON)}
