const SPREADSHEET_ID='17_HK3OGjiSa5UvjkzK96VPpIQM5c65yqOUPGGF1lKks';
const SHEET_NAME='planet_generation_log';
const TRIPO_BASE_URL='https://openapi.tripo3d.ai/v3';
function doGet(e){try{const action=String(e.parameter.action||'list').toLowerCase();if(action==='list')return json({success:true,data:listPlanets()});if(action==='tripo_status')return getTripoStatus(e.parameter.taskId);return json({success:false,message:'Unknown action'})}catch(err){return json({success:false,message:err.message})}}
function doPost(e){try{const body=JSON.parse(e.postData.contents||'{}');if(body.action==='ai_planet_design')return createAiPlanetDesign(body);if(body.action==='tripo_create')return createTripoTask(body.prompt);if(body.action==='create')return savePlanet(body);return json({success:false,message:'Unknown action'})}catch(err){return json({success:false,message:err.message})}}
function createAiPlanetDesign(body){
  if(!body.birthday||!/^[OCEAN]$/.test(body.type))throw new Error('生日或人格資料不完整');
  const schema={type:'object',additionalProperties:false,properties:{planetName:{type:'string'},astroSummary:{type:'string'},keywords:{type:'array',items:{type:'string'},minItems:3,maxItems:3},description:{type:'string'},tripoPrompt:{type:'string'}},required:['planetName','astroSummary','keywords','description','tripoPrompt']};
  const instructions='你是 INNERVERSE 的人格與幻想星球設計師。根據 Big Five 分數與生日的太陽星座象徵，創造一致且可視覺化的星球設定。生日只能可靠判斷太陽星座；沒有出生時間與地點時，禁止宣稱已計算月亮、上升、宮位或完整本命盤。占星內容只作創意與娛樂用途。輸出繁體中文，但 tripoPrompt 必須是清楚具體的英文。Prompt 必須描述單一完整球形行星、置中、全貌、無背景、無文字、無底座、無人物、無太空船、無額外行星，並包含材質、地形、生態、雲層、發光特徵、配色與 PBR 風格。';
  const input=JSON.stringify({nickname:safe(body.nickname),birthday:safe(body.birthday),primaryType:body.type,secondaryType:safe(body.secondaryType),bigFiveScores:body.scores||{},designConstraints:{keywords:'恰好三個、每個二至四個中文字',tripoPromptMaxCharacters:950}});
  const result=callOpenAI({model:getOpenAiModel(),instructions:instructions,input:input,text:{format:{type:'json_schema',name:'planet_design',strict:true,schema:schema}}});
  const design=JSON.parse(extractOpenAiText(result));
  if(!design.tripoPrompt||!Array.isArray(design.keywords)||design.keywords.length!==3)throw new Error('GPT 回傳的星球設計格式不完整');
  return json({success:true,design:design,model:getOpenAiModel(),completedAt:new Date().toISOString()});
}
function getOpenAiModel(){return PropertiesService.getScriptProperties().getProperty('OPENAI_MODEL')||'gpt-5-mini'}
function callOpenAI(payload){const apiKey=PropertiesService.getScriptProperties().getProperty('OPENAI_API_KEY');if(!apiKey)throw new Error('OPENAI_API_KEY 尚未設定');const response=UrlFetchApp.fetch('https://api.openai.com/v1/responses',{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+apiKey},payload:JSON.stringify(payload),muteHttpExceptions:true}),status=response.getResponseCode(),text=response.getContentText();let data;try{data=JSON.parse(text)}catch(_){throw new Error('OpenAI 回傳非 JSON 資料')}if(status<200||status>=300)throw new Error((data.error&&data.error.message)||('OpenAI API error '+status));return data}
function extractOpenAiText(response){let texts=[];(response.output||[]).forEach(function(item){(item.content||[]).forEach(function(content){if(content.type==='output_text'&&content.text)texts.push(content.text)})});if(!texts.length)throw new Error('GPT 沒有回傳星球設計');return texts.join('')}
function createTripoTask(prompt){if(!prompt||prompt.length<20)throw new Error('Planet prompt is missing');const result=callTripo('/generation/text-to-model','post',{prompt:String(prompt).slice(0,1000),model:'v3.1-20260211'});if(!result.data||!result.data.task_id)throw new Error('Tripo did not return a task ID');return json({success:true,taskId:result.data.task_id})}
function getTripoStatus(taskId){if(!taskId)throw new Error('Tripo task ID is missing');const result=callTripo('/tasks/'+encodeURIComponent(taskId),'get'),task=result.data||{},output=task.output||{},modelUrl=findAssetUrl(output,['model_url','pbr_model_url','base_model_url'],/\.(glb|gltf)(\?|$)/i),thumbnailUrl=findAssetUrl(output,['rendered_image_url','thumbnail_url'],/\.(png|jpe?g|webp)(\?|$)/i);return json({success:true,taskId:task.task_id||taskId,status:task.status||'unknown',progress:Number(task.progress||0),modelUrl:modelUrl,thumbnailUrl:thumbnailUrl,message:task.message||'',outputKeys:Object.keys(output)})}
function findAssetUrl(value,preferredKeys,pattern){if(!value)return'';if(typeof value==='string')return pattern.test(value)?value:'';if(typeof value!=='object')return'';for(let i=0;i<preferredKeys.length;i++){const direct=value[preferredKeys[i]];if(typeof direct==='string'&&direct)return direct}const keys=Object.keys(value);for(let j=0;j<keys.length;j++){const found=findAssetUrl(value[keys[j]],preferredKeys,pattern);if(found)return found}return''}
function callTripo(path,method,payload){const apiKey=PropertiesService.getScriptProperties().getProperty('TRIPO_API_KEY');if(!apiKey)throw new Error('TRIPO_API_KEY 尚未設定');const options={method:method,headers:{Authorization:'Bearer '+apiKey},muteHttpExceptions:true};if(payload){options.contentType='application/json';options.payload=JSON.stringify(payload)}const response=UrlFetchApp.fetch(TRIPO_BASE_URL+path,options),status=response.getResponseCode(),text=response.getContentText();let data;try{data=JSON.parse(text)}catch(_){throw new Error('Tripo 回傳非 JSON 資料')}if(status<200||status>=300||data.code!==0)throw new Error((data&&(data.message||data.msg))||('Tripo API error '+status));return data}
function savePlanet(body){
  if(!/^[OCEAN]$/.test(body.type))throw new Error('Invalid personality type');
  const s=body.scores||{},raw=body.rawScores||{},answers=body.answers||[],adjusted=body.adjustedAnswers||[];
  const values={id:body.id,nickname:body.nickname,birth_year:body.birthYear,birth_month:body.birthMonth,birth_day:body.birthDay,birthday:body.birthday,consent:body.consent,questions_json:JSON.stringify(body.questions||[]),answers_json:JSON.stringify(answers),adjusted_answers_json:JSON.stringify(adjusted),O_raw:raw.O,C_raw:raw.C,E_raw:raw.E,A_raw:raw.A,N_raw:raw.N,O_score:s.O,C_score:s.C,E_score:s.E,A_score:s.A,N_score:s.N,ranking_json:JSON.stringify(body.ranking||[]),primary_type:body.type,secondary_type:body.secondaryType,initial_keywords:JSON.stringify(body.initialKeywords||[]),ai_keywords:JSON.stringify(body.keywords||[]),planet_name:body.planetName,astro_summary:body.astroSummary,description:body.description,fallback_prompt:body.fallbackPrompt,final_tripo_prompt:body.prompt,openai_model:body.aiModel,ai_status:body.aiStatus,ai_completed_at:body.aiCompletedAt,ai_error:body.aiError,tripo_status:body.tripoStatus,tripo_task_id:body.tripoTaskId,tripo_progress:body.tripoProgress,tripo_completed_at:body.tripoCompletedAt,model_url:body.modelUrl,thumbnail_url:body.thumbnailUrl,generation_error:body.generationError,birthday_seed:body.birthdaySeed,seed:body.seed,created_at:body.createdAt,saved_at:new Date().toISOString(),full_payload_json:JSON.stringify(body)};
  for(let i=0;i<10;i++){values['q'+(i+1)+'_answer']=answers[i];values['q'+(i+1)+'_adjusted']=adjusted[i]}
  const sheet=getSheet();sheet.appendRow(LOG_HEADERS.map(function(key){return safe(values[key])}));return json({success:true,id:body.id,sheet:SHEET_NAME})
}
function listPlanets(){const rows=getSheet().getDataRange().getValues(),headers=rows[0]||[];return rows.slice(1).filter(function(r){return r[0]}).map(function(r){const x={};headers.forEach(function(h,i){x[h]=r[i]});return{id:String(x.id),nickname:String(x.nickname),type:String(x.primary_type),secondaryType:String(x.secondary_type),scores:{O:Number(x.O_score),C:Number(x.C_score),E:Number(x.E_score),A:Number(x.A_score),N:Number(x.N_score)},keywords:parseArray(x.ai_keywords),birthdaySeed:Number(x.birthday_seed),seed:Number(x.seed),status:String(x.tripo_status),tripoTaskId:String(x.tripo_task_id),modelUrl:String(x.model_url),thumbnailUrl:String(x.thumbnail_url),prompt:String(x.final_tripo_prompt),createdAt:x.created_at,planetName:String(x.planet_name),astroSummary:String(x.astro_summary),description:String(x.description)}})}
const LOG_HEADERS=['id','nickname','birth_year','birth_month','birth_day','birthday','consent','questions_json','answers_json','adjusted_answers_json','q1_answer','q1_adjusted','q2_answer','q2_adjusted','q3_answer','q3_adjusted','q4_answer','q4_adjusted','q5_answer','q5_adjusted','q6_answer','q6_adjusted','q7_answer','q7_adjusted','q8_answer','q8_adjusted','q9_answer','q9_adjusted','q10_answer','q10_adjusted','O_raw','C_raw','E_raw','A_raw','N_raw','O_score','C_score','E_score','A_score','N_score','ranking_json','primary_type','secondary_type','initial_keywords','ai_keywords','planet_name','astro_summary','description','fallback_prompt','final_tripo_prompt','openai_model','ai_status','ai_completed_at','ai_error','tripo_status','tripo_task_id','tripo_progress','tripo_completed_at','model_url','thumbnail_url','generation_error','birthday_seed','seed','created_at','saved_at','full_payload_json'];
function getSheet(){const book=SpreadsheetApp.openById(SPREADSHEET_ID);let sheet=book.getSheetByName(SHEET_NAME);if(!sheet){sheet=book.insertSheet(SHEET_NAME);sheet.appendRow(LOG_HEADERS);sheet.setFrozenRows(1);sheet.getRange(1,1,1,LOG_HEADERS.length).setFontWeight('bold').setBackground('#5b4cc4').setFontColor('#ffffff')}return sheet}
function parseArray(value){try{return JSON.parse(value||'[]')}catch(_){return[]}}
function safe(value){return value==null?'':String(value).slice(0,49000)}
function number(value){const n=Number(value);return isFinite(n)?n:0}
function json(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON)}
